# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68562b13a66b3322ee8afb5cd4e28f4177c268a650888533485fa50024953f4727846a1cf74cab591c86fc1dfd32db0031ca2fffcff8ad482da9cfb49fc6902a

test:
  secret_key_base: 48a0bb9254e92a35bf0bf91fb53b3f946ae977d73300adef54e50420d31b91fafe6d21d7de35a1ec6426fbf596b3d22afff194d246c93f4293d8e88e9416c418

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
